# Generated by Django 4.0.5 on 2022-06-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter course name', max_length=500, verbose_name='Course name')),
                ('description', models.TextField(help_text='Enter course description', verbose_name='Course description')),
                ('image', models.ImageField(help_text='Enter course image', upload_to='course-images', verbose_name='Course image')),
                ('teacher', models.CharField(help_text='Enter course teacher', max_length=500, verbose_name='Course teacher')),
                ('cost', models.PositiveIntegerField(help_text='Enter course price', verbose_name='Course price')),
                ('started', models.DateTimeField(help_text='Enter beginning of the course', verbose_name='Beginning of the course')),
            ],
            options={
                'verbose_name': 'Course ',
                'verbose_name_plural': 'Courses ',
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter user name', max_length=500, null=True, verbose_name='User Fullname')),
                ('t_id', models.IntegerField(help_text='Enter user telegram id', unique=True, verbose_name='User Telegram Id')),
                ('language', models.CharField(default='uz', help_text='Enter system language', max_length=10, verbose_name='User System Language')),
                ('phone', models.CharField(help_text='Enter user phone number', max_length=500, verbose_name='User phone number')),
                ('adress', models.CharField(help_text='Enter user address', max_length=500, verbose_name='User address')),
                ('course', models.ForeignKey(help_text='Enter chosen courses', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.courses', verbose_name='Courses')),
            ],
            options={
                'verbose_name': 'Client ',
                'verbose_name_plural': 'Clients ',
                'db_table': 'Clients',
            },
        ),
    ]
