# Generated by Django 4.0.5 on 2022-06-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_clients_t_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='course',
        ),
        migrations.AddField(
            model_name='clients',
            name='course',
            field=models.ManyToManyField(blank=True, help_text='Enter chosen courses', null=True, related_name='courses', to='app.courses', verbose_name='Courses'),
        ),
    ]
