# Generated by Django 4.0.5 on 2022-06-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_clients_course_clients_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='course',
            field=models.ManyToManyField(blank=True, help_text='Enter chosen courses', null=True, related_name='kurslar', to='app.courses', verbose_name='Courses'),
        ),
    ]
